apiVersion: configuration.konghq.com/v1
kind: KongPlugin
metadata:
  name: api-key-auth
  namespace: production
plugin: key-auth
config:
  key_in_header: true
  key_names:
    - apikey
---
apiVersion: configuration.konghq.com/v1
kind: KongConsumer
metadata:
  name: mobile-app-consumer
  namespace: production
  annotations:
    kubernetes.io/ingress.class: kong
username: mobile-app-prod
credentials:
  - mobile-app-key-auth-secret