apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: ms-administrative-core-ingress-qa
  namespace: qa
  annotations:
    kubernetes.io/ingress.class: "kong"
    konghq.com/plugins: "api-key-auth"
    konghq.com/strip-path: "true"         # <--- Remove o prefixo '/qa' antes de enviar para a API!
spec:
  ingressClassName: kong                # <--- ADICIONE ESTA LINHA AQUI!
  rules:
  - http:
      paths:
      - path: /qa                         # Tudo que começar com /qa
        pathType: Prefix
        backend:
          service:
            name: ms-administrative-core
            port:
              number: 8080