# helm/values-autopilot.yaml

# Ingress Controller do Kong
ingressController:
  enabled: true
  installCRDs: true

# Configuração do Proxy do Kong
proxy:
  enabled: true
  type: LoadBalancer
  # Anotação opcional para criar um IP estático ou NLB específico no GCP se desejar
  annotations:
    networking.gke.io/load-balancer-type: "External"
  
  resources:
  requests:
    cpu: "100m"     # 0.1 vCPU (suficiente para poucas requisições)
    memory: "256Mi" # 256 Megabytes
  limits:
    cpu: "500m"
    memory: "512Mi"

# Desabilita o Enterprise / Postgres se for usar o modo DB-less (mais simples e rápido)
env:
  database: "off"