ingressController:
  enabled: true
  installCRDs: false

proxy:
  enabled: true
  type: LoadBalancer
  annotations:
    networking.gke.io/load-balancer-type: "External"
  resources:
    requests:
      cpu: "100m"
      memory: "256Mi"
    limits:
      cpu: "500m"
      memory: "512Mi"

env:
  database: "postgres"
  pg_host: "postgres.production.svc.cluster.local"
  pg_database: "kong"
  pg_user: "kong"
  admin_listen: "127.0.0.1:8444 http2 ssl"
  pg_password:
    valueFrom:
      secretKeyRef:
        name: kong-postgres-secret
        key: pg_password

postgresql:
  enabled: false